import { WCAGAnalyzer } from '../core/WCAGAnalyzer.js';

export const accessibilityScoreTool = {
  definition: {
    name: 'accessibility_score',
    description: 'Calculate detailed accessibility score with metrics, grades, and recommendations',
    inputSchema: {
      type: 'object',
      properties: {
        code: {
          type: 'string',
          description: 'Code to score for accessibility',
        },
        format: {
          type: 'string',
          enum: ['html', 'react', 'vue', 'angular'],
          description: 'Code format',
          default: 'html',
        },
        detailed: {
          type: 'boolean',
          description: 'Include detailed breakdown',
          default: true,
        },
        generateBadge: {
          type: 'boolean',
          description: 'Generate markdown badge for GitHub',
          default: false,
        },
      },
      required: ['code'],
    },
  },
  
  handler: async (args: any) => {
    const { code, format = 'html', detailed = true, generateBadge = false } = args;
    
    try {
      const analyzer = new WCAGAnalyzer();
      
      // Analyze for all levels
      const levelA = await analyzer.analyze(code, { level: 'A', format });
      const levelAA = await analyzer.analyze(code, { level: 'AA', format });
      const levelAAA = await analyzer.analyze(code, { level: 'AAA', format });
      
      // Calculate scores
      const scores = calculateScores(levelA, levelAA, levelAAA);
      
      // Generate grade
      const grade = getGrade(scores.overall);
      const gradeEmoji = getGradeEmoji(grade);
      
      // Calculate metrics
      const metrics = calculateMetrics(levelAA);
      
      // Generate visualizations
      const scoreBar = generateScoreBar(scores.overall);
      const categoryChart = generateCategoryChart(metrics.categories);
      
      // Generate badge if requested
      const badge = generateBadge ? createBadge(scores.overall, grade) : '';
      
      // Build response
      let response = `
# 📊 Accessibility Score Report

## ${gradeEmoji} Overall Score: ${scores.overall}/100 (Grade: ${grade})

${scoreBar}

## 📈 Compliance Levels
- **Level A:** ${scores.levelA}% compliant ${getStatusIcon(scores.levelA)}
- **Level AA:** ${scores.levelAA}% compliant ${getStatusIcon(scores.levelAA)}
- **Level AAA:** ${scores.levelAAA}% compliant ${getStatusIcon(scores.levelAAA)}

## 🎯 Score Breakdown
${categoryChart}

## 📊 Detailed Metrics
- **Accessibility Issues:** ${metrics.totalIssues}
  - 🔴 Critical: ${metrics.critical}
  - 🟠 Serious: ${metrics.serious}
  - 🟡 Moderate: ${metrics.moderate}
  - 🟢 Minor: ${metrics.minor}

- **Elements Analyzed:** ${metrics.elementsAnalyzed}
- **Pass Rate:** ${metrics.passRate}%
- **Rules Tested:** ${metrics.rulesTested}
- **Rules Passed:** ${metrics.rulesPassed}
`;

      if (detailed) {
        response += `
## 🔍 Category Analysis
${generateCategoryAnalysis(metrics.categories)}

## 💡 Top Recommendations
${generateTopRecommendations(levelAA.violations)}

## 📈 Score Comparison
\`\`\`
Industry Average: 67/100
Your Score:       ${scores.overall}/100
Difference:       ${scores.overall > 67 ? '+' : ''}${scores.overall - 67}
\`\`\`

## 🏆 Achievements
${generateAchievements(scores, metrics)}
`;
      }

      if (generateBadge) {
        response += `
## 🏷️ GitHub Badge
Add this to your README.md:

\`\`\`markdown
${badge}
\`\`\`

Preview: ![Accessibility Score](https://img.shields.io/badge/A11y_Score-${scores.overall}%25-${getBadgeColor(scores.overall)})
`;
      }

      response += `
## 📋 Scoring Methodology
- **Critical issues:** -20 points each
- **Serious issues:** -10 points each
- **Moderate issues:** -5 points each
- **Minor issues:** -2 points each
- **Base score:** 100 points

## 🎯 Target Scores
- **Minimum Acceptable:** 60/100 (D)
- **Good:** 70/100 (C)
- **Very Good:** 80/100 (B)
- **Excellent:** 90/100 (A)
- **Perfect:** 100/100 (A+)

## ✅ Next Steps
${generateNextSteps(scores, metrics)}

---
*Generated by MCP WCAG Accessibility Tool*
*Score calculated based on WCAG 2.1 guidelines*
`;
      
      return {
        content: [
          {
            type: 'text',
            text: response,
          },
        ],
      };
    } catch (error) {
      return {
        content: [
          {
            type: 'text',
            text: `Error calculating score: ${error instanceof Error ? error.message : 'Unknown error'}`,
          },
        ],
      };
    }
  },
};

function calculateScores(levelA: any, levelAA: any, levelAAA: any): any {
  const calculateLevelScore = (result: any) => {
    const total = result.violations.length + result.passes.length;
    if (total === 0) return 100;
    return Math.round((result.passes.length / total) * 100);
  };
  
  const calculateOverall = (result: any) => {
    let score = 100;
    
    result.violations.forEach((violation: any) => {
      const penalty = getPenalty(violation.impact);
      score -= penalty * violation.nodes.length;
    });
    
    return Math.max(0, Math.min(100, score));
  };
  
  return {
    levelA: calculateLevelScore(levelA),
    levelAA: calculateLevelScore(levelAA),
    levelAAA: calculateLevelScore(levelAAA),
    overall: calculateOverall(levelAA),
  };
}

function getPenalty(impact: string): number {
  switch (impact) {
    case 'critical': return 20;
    case 'serious': return 10;
    case 'moderate': return 5;
    case 'minor': return 2;
    default: return 1;
  }
}

function getGrade(score: number): string {
  if (score >= 97) return 'A+';
  if (score >= 93) return 'A';
  if (score >= 90) return 'A-';
  if (score >= 87) return 'B+';
  if (score >= 83) return 'B';
  if (score >= 80) return 'B-';
  if (score >= 77) return 'C+';
  if (score >= 73) return 'C';
  if (score >= 70) return 'C-';
  if (score >= 67) return 'D+';
  if (score >= 63) return 'D';
  if (score >= 60) return 'D-';
  return 'F';
}

function getGradeEmoji(grade: string): string {
  if (grade.startsWith('A')) return '🌟';
  if (grade.startsWith('B')) return '⭐';
  if (grade.startsWith('C')) return '✨';
  if (grade.startsWith('D')) return '⚠️';
  return '❌';
}

function getStatusIcon(score: number): string {
  if (score >= 90) return '✅';
  if (score >= 70) return '🟡';
  return '❌';
}

function generateScoreBar(score: number): string {
  const filled = Math.round(score / 5);
  const empty = 20 - filled;
  const bar = '█'.repeat(filled) + '░'.repeat(empty);
  const color = score >= 80 ? '🟢' : score >= 60 ? '🟡' : '🔴';
  return `\`\`\`\n${color} [${bar}] ${score}%\n\`\`\``;
}

function calculateMetrics(result: any): any {
  const categories: any = {
    perceivable: { issues: 0, passed: 0 },
    operable: { issues: 0, passed: 0 },
    understandable: { issues: 0, passed: 0 },
    robust: { issues: 0, passed: 0 },
  };
  
  // Count by category
  result.violations.forEach((v: any) => {
    const category = getCategory(v.tags);
    if (category && categories[category]) {
      categories[category].issues += v.nodes.length;
    }
  });
  
  result.passes.forEach((p: any) => {
    const category = getCategory(p.tags);
    if (category && categories[category]) {
      categories[category].passed += 1;
    }
  });
  
  return {
    totalIssues: result.violations.reduce((sum: number, v: any) => sum + v.nodes.length, 0),
    critical: result.violations.filter((v: any) => v.impact === 'critical').length,
    serious: result.violations.filter((v: any) => v.impact === 'serious').length,
    moderate: result.violations.filter((v: any) => v.impact === 'moderate').length,
    minor: result.violations.filter((v: any) => v.impact === 'minor').length,
    elementsAnalyzed: result.violations.reduce((sum: number, v: any) => sum + v.nodes.length, 0) +
                      result.passes.reduce((sum: number, p: any) => sum + p.nodes.length, 0),
    passRate: Math.round((result.passes.length / (result.passes.length + result.violations.length)) * 100) || 0,
    rulesTested: result.passes.length + result.violations.length,
    rulesPassed: result.passes.length,
    categories,
  };
}

function getCategory(tags: string[]): string {
  if (tags.some(t => t.includes('perceivable'))) return 'perceivable';
  if (tags.some(t => t.includes('operable'))) return 'operable';
  if (tags.some(t => t.includes('understandable'))) return 'understandable';
  if (tags.some(t => t.includes('robust'))) return 'robust';
  
  // Fallback based on common patterns
  if (tags.some(t => t.includes('color') || t.includes('contrast') || t.includes('image'))) return 'perceivable';
  if (tags.some(t => t.includes('keyboard') || t.includes('focus') || t.includes('navigation'))) return 'operable';
  if (tags.some(t => t.includes('label') || t.includes('error') || t.includes('input'))) return 'understandable';
  if (tags.some(t => t.includes('aria') || t.includes('role') || t.includes('semantic'))) return 'robust';
  
  return 'perceivable'; // default
}

function generateCategoryChart(categories: any): string {
  let chart = '```\n';
  
  Object.entries(categories).forEach(([name, data]: [string, any]) => {
    const score = data.passed / (data.passed + data.issues) * 100 || 0;
    const barLength = Math.round(score / 10);
    const bar = '▓'.repeat(barLength) + '░'.repeat(10 - barLength);
    chart += `${name.padEnd(15)} ${bar} ${Math.round(score)}%\n`;
  });
  
  chart += '```';
  return chart;
}

function generateCategoryAnalysis(categories: any): string {
  let analysis = '';
  
  Object.entries(categories).forEach(([name, data]: [string, any]) => {
    const score = data.passed / (data.passed + data.issues) * 100 || 0;
    const status = score >= 80 ? '✅ Good' : score >= 60 ? '⚠️ Needs Work' : '❌ Poor';
    
    analysis += `
### ${name.charAt(0).toUpperCase() + name.slice(1)}
- Status: ${status}
- Issues: ${data.issues}
- Passed: ${data.passed}
- Score: ${Math.round(score)}%
`;
  });
  
  return analysis;
}

function generateTopRecommendations(violations: any[]): string {
  const top5 = violations
    .sort((a, b) => {
      const impactWeight = { critical: 4, serious: 3, moderate: 2, minor: 1 };
      return (impactWeight[b.impact as keyof typeof impactWeight] || 0) * b.nodes.length -
             (impactWeight[a.impact as keyof typeof impactWeight] || 0) * a.nodes.length;
    })
    .slice(0, 5);
  
  return top5.map((v, i) => 
    `${i + 1}. **Fix ${v.id}** (${v.impact}): ${v.help} - Affects ${v.nodes.length} element(s)`
  ).join('\n');
}

function generateAchievements(scores: any, metrics: any): string {
  const achievements = [];
  
  if (scores.overall >= 90) achievements.push('🏆 **A11y Champion** - Score 90+');
  if (scores.levelAA >= 100) achievements.push('🎯 **AA Perfect** - 100% WCAG AA compliance');
  if (metrics.critical === 0) achievements.push('✨ **No Critical Issues** - Zero critical violations');
  if (metrics.passRate >= 80) achievements.push('⭐ **High Pass Rate** - 80%+ rules passed');
  if (scores.overall >= scores.levelA) achievements.push('📈 **Progressive** - Exceeding Level A');
  
  return achievements.length > 0 ? achievements.join('\n') : '🎯 Keep improving to unlock achievements!';
}

function createBadge(score: number, grade: string): string {
  const color = getBadgeColor(score);
  return `![Accessibility Score](https://img.shields.io/badge/A11y_Score-${score}%2F100_${grade}-${color}?style=for-the-badge&logo=data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCI+PHBhdGggZmlsbD0iI2ZmZiIgZD0iTTEyIDJDNi40OCAyIDIgNi40OCAyIDEyczQuNDggMTAgMTAgMTAgMTAtNC40OCAxMC0xMFMxNy41MiAyIDEyIDJ6bTEgMTVoLTJ2LTJoMnYyem0wLTRoLTJWN2gydjZ6Ii8+PC9zdmc+)`;
}

function getBadgeColor(score: number): string {
  if (score >= 90) return 'brightgreen';
  if (score >= 80) return 'green';
  if (score >= 70) return 'yellowgreen';
  if (score >= 60) return 'yellow';
  return 'red';
}

function generateNextSteps(scores: any, metrics: any): string {
  const steps = [];
  
  if (metrics.critical > 0) {
    steps.push('1. 🔴 **Fix critical issues immediately** - These prevent basic accessibility');
  }
  if (metrics.serious > 0) {
    steps.push('2. 🟠 **Address serious violations** - Major barriers for users');
  }
  if (scores.levelA < 100) {
    steps.push('3. 📋 **Achieve Level A compliance** - Minimum accessibility standard');
  }
  if (scores.levelAA < 100) {
    steps.push('4. 📊 **Work towards Level AA** - Recommended standard');
  }
  if (scores.overall < 90) {
    steps.push('5. 🎯 **Aim for 90+ score** - Excellence in accessibility');
  }
  
  return steps.join('\n') || '✅ Excellent work! Consider Level AAA compliance for maximum accessibility.';
}
